name: 'AI Workflow Runner'
description: 'Run AI workflows with Node.js, Python, and Java runtime support'
author: 'TanNT'

inputs:
  workflow_path:
    description: 'Path to the workflow.md file (relative to workspace root)'
    required: true
  prompt:
    description: 'Input prompt to pass to the workflow (max 100KB)'
    required: false
    default: ''
  env_vars:
    description: 'JSON object of environment variables (max 64KB, 100 entries)'
    required: false
    default: '{}'
  timeout_minutes:
    description: 'Maximum execution time in minutes (default: 30)'
    required: false
    default: '30'

outputs:
  status:
    description: 'Execution status: success, failure, cancelled, or timeout'
  result:
    description: 'Workflow execution result as JSON string (max 900KB)'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'play-circle'
  color: 'green'
