name: Bug Report
description: Report a bug in AI Workflow Runner
title: '[Bug]: '
labels: ['bug']

body:
  - type: input
    id: version
    attributes:
      label: Action Version
      description: Which version of the action are you using?
      placeholder: 'e.g., v1.0.0'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: workflow
    attributes:
      label: Workflow Configuration
      description: The relevant workflow YAML that reproduces the issue.
      render: yaml
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any relevant log output.
      render: shell
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
